# Generated by Django 5.1.1 on 2024-10-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_app', '0002_tweetsentiment_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count_samples_for_retrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samples_number', models.IntegerField()),
            ],
        ),
    ]
